version: "3.9"
services:
  gateway:
    image: nginx
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    links:
      - api
      - web
  api:
    build: ./api # relative path to the API related Dockerfile
    environment:
      - REDIS_HOST=cache # using container name "cache"
      - REDIS_PORT=6379 # this is default redis port - we haven't specified any custom
    ports:
      - "3000:3000" # exposing port 3000 to "host" machine (making it "public")
    links:
      - cache # making "cache" service accessible to the API
  web:
    build: ./web
    ports:
      - "3001:3001"
  cache:
    image: redis
    volumes:
      - ./data/redis:/data # to keep data persistent between container start/stop/rebuild
    ports:
      - "6379:6379"
    